#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"
sudo apt update
sudo apt install -y nginx
sudo apt install -y sed
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo echo "Hello World!"  | sudo tee /var/www/html/index.nginx-debian.html

server "{
	listen 80 default_server;
	listen [[::]]:80 default_server;
	root /var/www/html;
	index index.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =301;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^/$ https://www.youtube.com/watch?v=QH2-TGUlwu4;
		return 301
	}
}"
service nginx restart
