#!/usr/bin/env bash
# Displays "infinity ..." plus SIGTERMs

touch /var/run/myscript.pid
trap "echo I hate the kill command; sudo rm -f /var/run/myscript.pid; exit" SIGTERM
trap "sudo rm -f /var/run/myscript.pid; exit" SIGQUIT
trap "echo Y U no love me?!; exit" SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
