#!/usr/bin/env bash
# configure the container to run nginx under nginx user on port 8080
sudo pkill apache2
sudo chmod 774 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
